drop table ACUDE cascade constraints;
drop table BACIA cascade constraints;
drop table CONTRIB_P_PLUVIOMETRICO_ACUDE cascade constraints;
drop table COTA_AREA_VOLUMEcascade constraints;
drop table ESTACAO_DE_QUALIDADEcascade constraints;
drop table MEDICAO_COTA_DIARIA cascade constraints;
drop table MEDICAO_PLUVIOMETRICA cascade constraints;
drop table POSTO_PLUVIOMETRICO cascade constraints;
drop table RIO cascade constraints;
drop table TELEFONES_USUARIO cascade constraints;
drop table USUARIO cascade constraints;
drop table V_DIARIOS_MED_PLUVIOMETRICA cascade constraints;
